name: sublime_groceria
description: "A Flutter project for Sublime Groceria, a comprehensive grocery list and shopping assistant application."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this dependency
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  dio: ^5.3.3
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  get_it: ^8.0.2
  flutter_spinkit: ^5.2.0
  form_field_validator: ^1.1.0
  go_router: ^14.6.0
  logger: ^2.3.0
  font_awesome_flutter: ^10.7.0
  bloc_concurrency: ^0.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.4
  http: ^1.2.2



flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/es.json
    - assets/lang/da.json
    - assets/images/